-- Listing 7.5.sql
-- Automatic number assignment

CREATE COLUMN TABLE test_identity (
                   a INT GENERATED BY DEFAULT AS IDENTITY, 
                   b VARCHAR(10));

INSERT INTO test_identity (b) VALUES ('One');
INSERT INTO test_identity (b) VALUES ('Two');
INSERT INTO test_identity (a,b) VALUES (3, 'Three');
INSERT INTO test_identity (b) VALUES ('Four');

SELECT * FROM test_identity;
