CREATE TABLE Countries (
    COUNTRY VARCHAR(2) NOT NULL primary key,
    TEXT VARCHAR(255) NOT NULL
);


INSERT INTO Countries (COUNTRY, TEXT) VALUES ('AF', 'Afghanistan');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('EG', 'Egypt');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('AL', 'Albania');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('DZ', 'Algeria');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('AD', 'Andorra');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('AO', 'Angola');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('AR', 'Argentina');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('AM', 'Armenia');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('AU', 'Australia');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('AT', 'Austria');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('AZ', 'Azerbaijan');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('BH', 'Bahrain');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('BD', 'Bangladesh');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('BY', 'Belarus');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('BE', 'Belgium');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('BZ', 'Belize');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('BJ', 'Benin');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('BO', 'Bolivia');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('BW', 'Botswana');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('BR', 'Brazil');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('BN', 'Brunei');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('BG', 'Bulgaria');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('BF', 'Burkina Faso');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('BI', 'Burundi');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('KH', 'Cambodia');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('CM', 'Cameroon');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('CA', 'Canada');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('CF', 'Central African Republic');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('TD', 'Chad');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('CL', 'Chile');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('CN', 'China');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('CO', 'Colombia');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('KM', 'Comoros');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('CD', 'Democratic Republic of the Congo');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('CG', 'Republic of the Congo');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('CR', 'Costa Rica');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('HR', 'Croatia');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('CU', 'Cuba');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('CY', 'Cyprus');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('CZ', 'Czech Republic');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('DK', 'Denmark');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('DJ', 'Djibouti');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('DO', 'Dominican Republic');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('EC', 'Ecuador');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('SV', 'El Salvador');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('ER', 'Eritrea');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('EE', 'Estonia');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('ET', 'Ethiopia');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('FI', 'Finland');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('FR', 'France');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('GA', 'Gabon');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('GM', 'Gambia');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('GE', 'Georgia');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('DE', 'Germany');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('GH', 'Ghana');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('GR', 'Greece');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('GT', 'Guatemala');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('GN', 'Guinea');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('GY', 'Guyana');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('HT', 'Haiti');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('HN', 'Honduras');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('HU', 'Hungary');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('IS', 'Iceland');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('IN', 'India');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('ID', 'Indonesia');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('IR', 'Iran');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('IQ', 'Iraq');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('IE', 'Ireland');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('IL', 'Israel');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('IT', 'Italy');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('JM', 'Jamaica');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('JP', 'Japan');
INSERT INTO Countries (COUNTRY, TEXT) VALUES ('JO', 'Jordan');

